### PR TITLE
Make icons change layout too [#1911]

### LINKED ISSUE #1911: "Grid" and "Full" icons are not click targets, only the text responds to clicks
### Current Behavior
In the Auspice sidebar, in the "Display" section, clicking on the icons to the left of "FULL" or "GRID" does not do anything. 

Screenshot 2024-11-19 at 14 52 46

Specifically, in the screenshot, clicking the blue circles loads the expected layout; clicking the red hexes does nothing. 

### Expected behavior
Clicking the icons should do the same thing as clicking the word. 

### How to reproduce
Steps to reproduce the current behavior:
1. Visualize a tree
2. Click the icon next to "Grid"
3. See that nothing happens, get increasingly frustrated
4. Click the text "Grid", see the layout change, think, "boy that's poor a11y isn't it"

### PR DESCRIPTION
**Pull request by genehack**
## Description of proposed changes

This PR adds wrapping `<span>`s to the grid/full buttons in the layout sub-panel, so clicking the icons changes the layout, just like clicking the words. 

## Related issue(s)

Closes #1911

## Checklist

- [ ] Checks pass
- [ ] If making user-facing changes, add a message in [CHANGELOG.md](https://github.com/nextstrain/auspice/blob/HEAD/CHANGELOG.md) summarizing the changes in this PR
- [ ] (to be done by a Nextstrain team member) [Create preview PRs on downstream repositories][1].

[1]: https://github.com/nextstrain/auspice/blob/-/DEV_DOCS.md#test-on-downstream-repositories

### CODE REVIEW

File: src/components/controls/panel-layout.js [hunk 1]
```diff
@@ -27,27 +27,31 @@ class PanelLayouts extends React.Component {
...
             analyticsControlsEvent("change-layout-full");
             this.props.dispatch({ type: CHANGE_PANEL_LAYOUT, data: "full" });
           }}
         >
-          <ButtonText>{t("sidebar:full")}</ButtonText>
-        </SidebarButton>
+          <PanelsFullIcon width={22} selected={this.props.panelLayout === "full"}/>
+          <SidebarButton selected={this.props.panelLayout === "full"}>
+            <ButtonText>{t("sidebar:full")}</ButtonText>
+          </SidebarButton>
```
Comment (victorlin) [inline src/components/controls/panel-layout.js:40]: (nit)

A button nested in a clickable span is presented as two separate selectable items to a screen reader (or [Vimium](https://vimium.github.io) in my case). This is what I see on the PR review app:

image

The same desired effect can be achieved by placing the icon within the button while maintaining a single selectable item and adjusting the styles:

image

```jsx
<SidebarButton
  selected={this.props.panelLayout === "full"}
  style={{cursor: "pointer"}}
  onClick={…}
>
  <PanelsFullIcon width={22} selected={this.props.panelLayout === "full"}/>
  <ButtonText>{t("sidebar:full")}</ButtonText>
</SidebarButton>
```

Comment (genehack) [reply src/components/controls/panel-layout.js:40]: > By placing the icon within the button instead

Yeah, I tried that, the styling got janky. I will look at it again tomorrow.

Comment (genehack) [reply src/components/controls/panel-layout.js]: FSVO "tomorrow" — styling still isn't _quite_ identical, but I'm not sure the difference that's there is worth sweating over further? 

Opinions (and alternative implemantions) welcome...

Comment (victorlin) [reply src/components/controls/panel-layout.js]: Here's my attempt at styling. Less diff compared to original code: ef5387f8bf63baded997c613ef43c559b452e496

image


Not easy to get rid of the added whitespace which comes from `SidebarButton`'s [margin](https://github.com/nextstrain/auspice/blob/ef5387f8bf63baded997c613ef43c559b452e496/src/components/controls/styles.js#L74) since it's used elsewhere too. But I think it's good enough.

Comment (genehack) [reply src/components/controls/panel-layout.js]: squashed that commit onto this branch and force-pushed.

**Review by victorlin — APPROVED** [review]
Changelog entry, maybe?

**Comment by genehack** [comment]
> Changelog entry, maybe?

Added & force-pushed — in a "NEXT" section, as I don't think this change by itself deserves a release?

**Comment by victorlin** [comment]
No need for a new section header, it is automatically added in the release script:

https://github.com/nextstrain/auspice/blob/bf2481679045fe969185429877d37fd2620de620/releaseNewVersion.sh#L80

**Comment by genehack** [comment]
ah, okay, cool, removed, re-pushed.

**Review by victorlin — APPROVED** [review]
