### PR TITLE
Fix new metadata tip label

### LINKED ISSUE #1176: Drag and drop tsv metadata not adding color by option to dropdown
**Current Behavior**  
From @trvrb :
> drag-and-drop metadata is working on auspice.us, but is perhaps broken on nextstrain.org.

**Expected behavior**  
Drag and drop should work to add a color by option to the dropdown upon dropping and parsing a TSV. This works on auspice.us

**How to reproduce**  
Reproduce bug:
1. On current master, run `auspice view --datasetDir examples` and go to `http://localhost:4000/minimal/v2`
2. When that has loaded, drag and drop https://gist.github.com/eharkins/c89ae185f164c2af3ae6668ffa8f55c2
4. Note that `collection` is *not* an option to select in the sidebar's Color By dropdown

Reproduce correct behavior:
1. Go to auspice.us 
2. Drag and drop https://github.com/nextstrain/auspice/blob/master/examples/minimal_v2.json 
3. When that has loaded, drag and drop https://gist.github.com/eharkins/c89ae185f164c2af3ae6668ffa8f55c2 
4. Note that `collection` is an option to select in the sidebar's Color By dropdown

**Possible solution**  
Differing versions of auspice (2.17.0 in nextstrain.org and 2.12.0 in auspice.us) are my best guess as to the difference in behavior - several hundred commits in auspice separate the two. One way to solve this is to try and find the commit that broke it, another way is more directly debugging the current code.

**Your environment: if browsing Nextstrain online**  
 - Operating system:  macOS High Sierra 10.13.4 (17E199)
 - Browser: Chrome Version 83.0.4103.106 (Official Build) (64-bit)

### PR DESCRIPTION
**Pull request by joverlee521**
## Description of proposed changes

Ensures that new metadata fields added to the tree are included as new tip labels.

## Related issue(s)

Resolves https://github.com/nextstrain/auspice/issues/1844

## Checklist

- [x] Checks pass
- [x] If making user-facing changes, add a message in [CHANGELOG.md](https://github.com/nextstrain/auspice/blob/HEAD/CHANGELOG.md) summarizing the changes in this PR
- [x] (to be done by a Nextstrain team member) [Create preview PRs on downstream repositories][1].

[1]: https://github.com/nextstrain/auspice/blob/-/DEV_DOCS.md#test-on-downstream-repositories

### CODE REVIEW

**Review by genehack — APPROVED** [review]

File: src/util/treeJsonProcessing.js [hunk 1]
```diff
@@ -16,7 +16,7 @@ const pseudoRandomName = () => (Math.random()*1e32).toString(36).slice(0, 6);
  *
  * side-effects: node.hasChildren (bool) and node.arrayIdx (INT) for each node in nodes
  */
-const processNodes = (nodes) => {
+export const processNodes = (nodes) => {
```
Comment (jameshadfield) [inline src/util/treeJsonProcessing.js:19]: When I extended this to also return `nodeAttrKeys` I didn't foresee it being used outside of the initial dataset load. Rather than calling this function, why not simply add the incoming `action.newNodeAttrs` to the existing ones?

Comment (joverlee521) [reply src/util/treeJsonProcessing.js]: Ah, I honestly just didn't dig deep enough here! Updated in [force-push](https://github.com/nextstrain/auspice/compare/0f2a10fcd11b501f696279d63996c4d871c57a3d..c2125254e251ed1cda169d88128280389f46dccf)

**Review by jameshadfield — APPROVED** [review]
This looks good from inspection, but I haven't tested it. Please merge if you're happy with the behaviour.
