### PR TITLE
[tanglegrams] fix browser-specific bug where the RHS tree wasn't displayed

### LINKED ISSUE #1755: [tanglegrams] Unable to view using Safari
### Current Behavior
Unable to view [tangletree](https://nextstrain.org/flu/seasonal/h3n2/ha/2y:flu/seasonal/h3n2/na/2y) using Safari, but works fine in both Firefox and Chrome. 

Screenshot 2024-02-22 at 10 51 04 AM

I can see some errors in the developer console

Screenshot 2024-02-22 at 10 55 43 AM

### Your environment: if browsing Nextstrain online
 - Operating system: macOS 13.6.3
 - Browser: Safari 17.2.1

### Additional context
This bug was reported during today's Nextstrain office hours. User was trying to view a tangletree via auspice.us using Safari.

### PR DESCRIPTION
**Pull request by jameshadfield**
Fixes a browser-specific bug where the invalid `<rect>` would cause the entire RHS tree to not be displayed.

Tested on Safari 17.4.1, Firefox 126 & Chrome 123

Closes #1755
- [ ] Checks pass
- [x] If making user-facing changes, add a message in [CHANGELOG.md](https://github.com/nextstrain/auspice/blob/HEAD/CHANGELOG.md) summarizing the changes in this PR

### CODE REVIEW

File: src/components/tree/phyloTree/renderers.js [hunk 1]
```diff
@@ -374,7 +374,11 @@ export const branchStrokeForHover = function branchStrokeForHover(d) {
  * in practice, elements (or portions of elements) render outside this.
  */
 export const setClipMask = function setClipMask() {
-  const [xMin, xMax, yMin, yMax] = [...this.xScale.range(), ...this.yScale.range()];
+  const [yMin, yMax] = this.yScale.range();
+  // for the RHS tree (if there is one) ensure that xMin < xMax, else width<0 which some
+  // browsers don't like. See <https://github.com/nextstrain/auspice/issues/1755>
+  let [xMin, xMax] = this.xScale.range();
+  if (xMin>xMax) [xMin, xMax] = [xMax, xMin];
```
Comment (genehack) [inline src/components/tree/phyloTree/renderers.js:381]: Random thought: are you 100% sure `xMin` and `xMax` are *always* going to be number or do you need to do something like this to be safe:

```suggestion
  if (parseInt(xMin,10)>parseInt(xMax,10)) [xMin, xMax] = [xMax, xMin];
```

Comment (jameshadfield) [reply src/components/tree/phyloTree/renderers.js:381]: It _should_ be - it's a bug if not - but I'll add this change to cover all bases. My hope is that TS would provide guarantees here, and so if there is a bug somewhere it'll identify it for us, but I've not had ~any experience with TS + d3 so time will tell!

Comment (jameshadfield) [reply src/components/tree/phyloTree/renderers.js]: [Updated in force-push](https://github.com/nextstrain/auspice/compare/fcc3b68f23a2623de5ce0cbebf98ac2b5bda9c10..a17fb0b51a72ab0611b449bcc5e931fc23ea64b0)
